apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-edit
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - pods
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - "*"
